import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, CircleUserRound, Layers3 } from "lucide-react";
import { WinlaMark } from "@/components/winlaos/brand";

export const metadata: Metadata = { title: "Getting started with WinlaOS", robots: { index: false, follow: false } };

const steps = [
  { number: "01", title: "Create your account", description: "Sign up with your work email. Confirm your address before signing in." },
  { number: "02", title: "Tell us about your business", description: "Add your workspace name, business type and the best way to reach you." },
  { number: "03", title: "Choose your first focus", description: "Start with customers, conversations or day-to-day operations. You can add more later." },
];

export default function WinlaOsOnboardingPage() {
  return <main className="winla-page min-h-screen bg-[#faf9f5] text-[#173b32]"><header className="mx-auto flex h-[76px] max-w-6xl items-center justify-between px-5 sm:px-8"><WinlaMark/><Link href="/winlaos" className="inline-flex items-center gap-2 text-sm text-[#647269]"><ArrowLeft size={15}/> WinlaOS overview</Link></header><section className="mx-auto max-w-4xl px-5 pb-20 pt-12 sm:px-8 sm:pt-16"><p className="winla-eyebrow">A thoughtful start</p><h1 className="mt-4 max-w-3xl font-display text-4xl font-semibold leading-tight tracking-tight sm:text-5xl">Get your workspace ready, one step at a time.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#6c7a70]">A quick overview of what happens after signup. Workspace changes are not yet connected to persistence in this UI workstream.</p><ol className="mt-10 space-y-4">{steps.map(({number,title,description},i)=><li key={number} className="flex gap-4 rounded-2xl border border-[#e6e3d9] bg-white p-5 sm:gap-6 sm:p-6"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-full font-mono text-xs ${i===0?"bg-[#173b32] text-white":"bg-[#f1f0e8] text-[#718076]"}`}>{i===0?<Check size={17}/>:number}</span><div><h2 className="font-semibold">{title}</h2><p className="mt-1.5 max-w-xl text-sm leading-6 text-[#748077]">{description}</p></div><span className="ml-auto hidden text-[10px] font-semibold uppercase tracking-wider text-[#9aa198] sm:block">{i===0?"Start here":"Next"}</span></li>)}</ol><div className="mt-7 rounded-2xl border border-[#ead9c9] bg-[#f8f0e8] p-5"><div className="flex gap-3"><CircleUserRound className="mt-0.5 shrink-0 text-[#a65435]" size={19}/><div><h2 className="text-sm font-semibold">What is connected today?</h2><p className="mt-1.5 text-sm leading-6 text-[#756b60]">Account creation and sign-in depend on the separate authentication branch. Business profile, organization creation and invitations are UI-only here and will not be saved.</p></div></div></div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-[#173b32] px-6 text-sm font-semibold text-white">Create account <ArrowRight size={16}/></Link><Link href="/login" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl border border-[#dadbd1] bg-white px-6 text-sm font-semibold">Sign in</Link><Link href="/winlaos/preview" className="inline-flex h-12 items-center justify-center gap-2 px-3 text-sm font-medium text-[#718076]">Explore preview <Layers3 size={15}/></Link></div></section></main>;
}
