import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, Compass, Layers3, ShieldCheck } from "lucide-react";
import { WinlaMark } from "@/components/winlaos/brand";

export const metadata: Metadata = { title: "WinlaOS", description: "A calmer way to manage the everyday work behind your business." };

const features = [
  { icon: Compass, title: "Know what needs attention", text: "Keep customer conversations and follow-ups from getting lost in the rush." },
  { icon: Layers3, title: "Bring the moving parts together", text: "Sales, customers, stock and team workflows can live in one clear workspace." },
  { icon: ShieldCheck, title: "Built around your business", text: "Start with the details and tools that fit how your business already works." },
];

export default function WinlaOsPage() {
  return <main className="winla-page min-h-screen bg-[#faf9f5] text-[#173b32]">
    <header className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 sm:px-8"><WinlaMark/><nav aria-label="WinlaOS" className="hidden items-center gap-7 text-sm text-[#68766c] md:flex"><a href="#how-it-works" className="hover:text-[#173b32]">How it works</a><a href="#tools" className="hover:text-[#173b32]">What you can manage</a><Link href="/systems" className="hover:text-[#173b32]">Winlerr systems</Link></nav><div className="flex items-center gap-2"><Link href="/login" className="hidden rounded-xl px-4 py-2.5 text-sm font-medium text-[#52665d] hover:bg-[#f0efe8] sm:block">Sign in</Link><Link href="/signup" className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#173b32] px-4 text-sm font-semibold text-white transition hover:bg-[#244f41]">Get started <ArrowRight size={15}/></Link></div></header>
    <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-12 sm:px-8 sm:pt-20 lg:grid-cols-[1fr_0.96fr] lg:items-center lg:pb-28">
      <div><p className="winla-eyebrow">A clearer way to run your business</p><h1 className="mt-5 max-w-2xl font-display text-[42px] font-semibold leading-[1.05] tracking-[-.035em] sm:text-6xl">The everyday work of your business, <span className="text-[#a65435]">in one place.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-[#69776d] sm:text-lg sm:leading-8">WinlaOS brings customers, conversations and operations into a calm workspace, so you can spend less time keeping track and more time moving forward.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-[#173b32] px-6 text-sm font-semibold text-white hover:bg-[#244f41]">Create your workspace <ArrowRight size={16}/></Link><Link href="/winlaos/onboarding" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl border border-[#dadbd1] bg-white px-6 text-sm font-semibold text-[#29493b] hover:bg-[#f3f3ed]">See how it works <ArrowUpRight size={15}/></Link></div><div className="mt-6 flex items-center gap-2 text-xs text-[#78847b]"><Check size={15} className="text-[#588268]"/> Start with your business basics. Add tools when you are ready.</div></div>
      <div className="relative rounded-[28px] border border-[#e4e1d6] bg-[#f1eee5] p-3 shadow-[0_22px_60px_rgba(32,56,42,.09)] sm:p-5"><div aria-hidden="true" className="absolute -right-5 -top-5 h-24 w-24 rounded-full border border-[#ddc2aa]"/><div className="overflow-hidden rounded-[20px] border border-[#e5e2d9] bg-[#faf9f5]"><div className="flex h-12 items-center justify-between border-b border-[#e9e6dd] px-4"><span className="flex items-center gap-2 text-xs font-semibold"><i className="h-2 w-2 rounded-full bg-[#729478]"/> Your workspace</span><span className="text-[10px] text-[#869087]">OVERVIEW</span></div><div className="grid min-h-[360px] grid-cols-[104px_1fr] sm:grid-cols-[128px_1fr]"><aside className="space-y-2 border-r border-[#e9e6dd] bg-[#f5f4ef] p-3"><div className="mb-4 h-7 rounded-lg bg-[#e9e8df]"/>{["Overview","Customers","Inbox","Sales","Reports"].map((x,i)=><div key={x} className={`rounded-lg px-2 py-2 text-[9px] sm:text-[10px] ${i===0?"bg-[#e3eae0] font-semibold text-[#325841]":"text-[#899189]"}`}>{x}</div>)}</aside><div className="p-4 sm:p-5"><p className="text-[10px] text-[#859087]">YOUR BUSINESS AT A GLANCE</p><div className="mt-1 text-lg font-semibold tracking-tight sm:text-xl">Good morning.</div><div className="mt-1 text-[10px] text-[#8b948d]">A clear picture of what’s happening today.</div><div className="mt-5 grid grid-cols-2 gap-2">{[["New enquiries","—"],["Customers","—"],["Sales this month","—"],["Follow-ups due","—"]].map(([label,value])=><div key={label} className="rounded-xl border border-[#e9e6dd] bg-white p-3"><p className="text-[9px] text-[#879087]">{label}</p><p className="mt-2 text-xl font-semibold text-[#315441]">{value}</p></div>)}</div><div className="mt-3 rounded-xl border border-[#e9e6dd] bg-white p-3.5"><div className="flex items-center justify-between"><span className="text-[10px] font-semibold">Make this workspace yours</span><span className="rounded-full bg-[#f5eee3] px-2 py-1 text-[8px] text-[#8a785e]">STEP 1 OF 3</span></div><div className="mt-3 h-1 rounded-full bg-[#eeede7]"><div className="h-full w-1/3 rounded-full bg-[#789778]"/></div></div><div className="mt-3 grid grid-cols-2 gap-2"><div className="h-[72px] rounded-xl border border-[#e9e6dd] bg-white p-3"><div className="h-2 w-1/2 rounded bg-[#eeede7]"/><div className="mt-3 h-2 w-4/5 rounded bg-[#f2f1eb]"/></div><div className="h-[72px] rounded-xl border border-[#e9e6dd] bg-white p-3"><div className="h-2 w-1/2 rounded bg-[#eeede7]"/><div className="mt-3 h-2 w-3/5 rounded bg-[#f2f1eb]"/></div></div></div></div></div><Link href="/winlaos/preview" className="mt-3 flex items-center justify-center gap-1.5 text-xs font-medium text-[#65756b] hover:text-[#a65435]">Open interactive product preview <ArrowUpRight size={13}/></Link></div>
    </section>
    <section id="tools" className="border-y border-[#ebe8df] bg-white"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20"><div className="max-w-xl"><p className="winla-eyebrow">Made for the whole picture</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-tight sm:text-4xl">Less juggling. More room to grow.</h2><p className="mt-3 text-sm leading-6 text-[#6c7a70]">WinlaOS is the home for the practical details that keep a business moving.</p></div><div className="mt-9 grid gap-4 md:grid-cols-3">{features.map(({icon:Icon,title,text})=><article key={title} className="rounded-2xl border border-[#e9e7df] bg-[#fcfbf8] p-5 sm:p-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf2e9] text-[#53745c]"><Icon size={19}/></span><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#758078]">{text}</p></article>)}</div></div></section>
    <section id="how-it-works" className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 sm:py-20 md:grid-cols-[.8fr_1.2fr]"><div><p className="winla-eyebrow">Start simply</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-tight">One step at a time.</h2><p className="mt-3 text-sm leading-6 text-[#6c7a70]">No complicated rollout. Build the foundation, then add the tools that solve your next problem.</p><Link href="/winlaos/onboarding" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#a65435]">Explore onboarding <ArrowRight size={15}/></Link></div><div className="grid gap-3 sm:grid-cols-3">{[{n:"01",t:"Create your login",b:"Use your email to get started securely."},{n:"02",t:"Set up your workspace",b:"Add your business name and working context."},{n:"03",t:"Choose what comes next",b:"Explore modules as your needs grow."}].map(({n,t,b})=><article key={n} className="rounded-2xl border border-[#e6e3d9] bg-white p-5"><span className="font-mono text-xs text-[#a65435]">{n}</span><h3 className="mt-6 text-sm font-semibold">{t}</h3><p className="mt-2 text-xs leading-5 text-[#758078]">{b}</p></article>)}</div></section>
    <footer className="border-t border-[#e7e4db] bg-[#f4f2eb]"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-7 sm:flex-row sm:items-center sm:justify-between sm:px-8"><WinlaMark/><div className="flex flex-wrap gap-5 text-xs text-[#738076]"><Link href="/">Winlerr home</Link><Link href="/get-started">Free website</Link><Link href="/login">Sign in</Link></div><p className="text-xs text-[#929a92]">A Winlerr product · Zambia</p></div></footer>
  </main>;
}
